app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Routes File
|--------------------------------------------------------------------------
|
| Here is where you will register all of the routes in an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', function () {
    return view('welcome');
});

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| This route group applies the "web" middleware group to every route
| it contains. The "web" middleware group is defined in your HTTP
| kernel and includes session state, CSRF protection, and more.
|
*/

Route::group(['middleware' => 'web'], function () {
    Route::auth();
    Route::group(['middleware' => 'auth', 'namespace' => 'Backend', 'prefix' => config('backend.path')], function () {
        Route::get('/', ['as' => 'admin.dashboard.index', 'uses' => 'DashboardController@index']);
        Route::resource('/categories', 'CategoryController');
        Route::resource('/posts', 'PostController');
    });
    Route::get('/home', 'HomeController@index');
    Route::get('/test', function () {
        Log::debug('debuger');
    });
});

app/Models/Category.php
<?php

namespace App\Models;

use Baum\Node;
use App\Models\Traits\CategoryQuery;

/**
 * Category
 */
class Category extends Node
{
    use CategoryQuery;

    /**
     * Table name.
     *
     * @var string
     */
    protected $table = 'categories';

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = ['name', 'slug', 'public', 'description'];

    /**
     * Column name which stores reference to parent's node.
     *
     * @var string
     */
    protected $parentColumn = 'parent_id';

    /**
     * Column name for the left index.
     *
     * @var string
     */
    protected $leftColumn = 'lft';

    /**
     * Column name for the right index.
     *
     * @var string
     */
    protected $rightColumn = 'rgt';

    /**
     * Column name for the depth field.
     *
     * @var string
     */
    protected $depthColumn = 'depth';

    /**
     * Column to perform the default sorting
     *
     * @var string
     */
    protected $orderColumn = null;

    /**
     * With Baum, all NestedSet-related fields are guarded from mass-assignment
     * by default.
     *
     * @var array
     */
    protected $guarded = ['id', 'parent_id', 'lft', 'rgt', 'depth'];

    /**
     * Columns which restrict what we consider our Nested Set list
     *
     * @var array
     */
    protected $scoped = [];

    public function parent()
    {
        return $this->belongsTo(Category::class, 'parent_id', 'id');
    }

    public function posts()
    {
        return $this->belongsToMany(Post::class);
    }
}

app/Http/Controllers/Backend/CategoryController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Requests\Backend\CategoryRequest as Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\MessageBag;

use App\Models\Category;
use App\Models\Repositories\CategoryRepository;


class CategoryController extends Controller
{

    /**
     * @var CategoryRepository
     */
    private $categoryRepository;

    /**
     * @var MessageBag
     */
    private $messageBag;

    public function __construct(CategoryRepository $categoryRepository, MessageBag $messageBag)
    {
        $this->categoryRepository = $categoryRepository;
        $this->messageBag = $messageBag;
    }


    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $categories = $this->categoryRepository->buildOption();
        $tableCategoriesData = $this->categoryRepository->buildTableTree();
        return view('backend.limitless.category.index', compact('categories', 'tableCategoriesData'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->has('slug') ? '' : $request->merge(['slug' => str_slug($request->get('name'), '-')]);
        $this->categoryRepository->createCate($request->except('_token'));
        $this->messageBag->add('swalSuccess', 'You has created new category.');
        return redirect()->back()->withErrors($this->messageBag);
    }

    /**
     * Display the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $category = $this->categoryRepository->find($id);
        if ($category->isRoot()) {
            return redirect()->back();
        }
        $categories = $this->categoryRepository->buildOption($id);
        return view('backend.limitless.category.edit', compact('categories', 'category'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->categoryRepository->updateCate($request->except(['_token', '_method']), $id);
        $this->messageBag->add('swalSuccess', 'You has created new category.');
        return redirect()->back()->withErrors($this->messageBag);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        dd($this->categoryRepository->buildOption());
        $cat = Category::find($id);
        if (!$cat->canDelete()) {
            return redirect()->back()->withErrors($cat->getMessages());
        }
    }

}

resources/views/backend/limitless/category/edit.blade.php
@extends('backend.limitless.app')

{{--Begin Config--}}
@section('app.title','Shrym CMS - Admin Dashboard.')
{!! Form::component('fieldError', 'backend.limitless.partials.components.input-validate-error', ['name']) !!}
{{--End Config--}}
@section('page-title')
    <i class="icon-arrow-left52 position-left"></i> <span class="text-semibold">Categories</span> - Create
@endsection
@section('breadcrumb')
    <div class="breadcrumb-line">
        <ul class="breadcrumb">
            <li><a href="{!! route('admin.dashboard.index') !!}"><i class="icon-home2 position-left"></i> Home</a></li>
            <li><a href="{!! route('admin.categories.index') !!}">Categories</a></li>
            <li class="active">{{ $category->name }}</li>
        </ul>
    </div>
@endsection
@section('content')
    <div class="row">
        <div class="col-md-12">
            {!! Form::model($category,['route' => ['admin.categories.update', $category->id], 'method' => 'PUT']) !!}
            <div class="panel panel-flat">
                <div class="panel-heading">
                    <h5 class="panel-title">Edit category</h5>
                </div>

                <div class="panel-body">
                    <div class="form-group">
                        <label>Name:</label>
                        {!! Form::text('name', null,['class' => 'form-control', 'placeholder' => 'Category Name']) !!}
                        @if ($errors->has('name'))
                            {!! Form::fieldError('name') !!}
                        @endif
                    </div>

                    <div class="form-group">
                        <label>Slug:</label>
                        {!! Form::text('slug', null,['class' => 'form-control', 'placeholder' => 'Category Slug']) !!}
                        <span class="help-block">Default slug is: <span id="default-slug" class="text-blue-700"></span></span>
                        @if ($errors->has('slug'))
                            {!! Form::fieldError('slug') !!}
                        @endif
                    </div>

                    <div class="form-group">
                        <label>Parrent Category:</label>
                        {!! Form::select('parent_id', $categories,null, ['class' => 'select']) !!}
                        @if ($errors->has('parent_id'))
                            {!! Form::fieldError('parent_id') !!}
                        @endif
                    </div>

                    <div class="form-group">
                        <label class="display-block">Public:</label>

                        <label class="radio-inline">
                            {!! Form::radio('public', '1', true,['class'=>'styled']) !!} Active
                        </label>

                        <label class="radio-inline">
                            {!! Form::radio('public', '0', false, ['class'=>'styled']) !!} Not active
                        </label>
                    </div>

                    <div class="form-group">
                        <label>Description:</label>
                        {!! Form::textarea('description',null,['rows' => 5, 'cols' => 5, 'class' => 'form-control', 'placeholder' => 'Category description']); !!}
                    </div>

                    <div class="text-right">
                        <button type="submit" class="btn btn-primary">Create <i
                                    class="icon-arrow-right14 position-right"></i></button>
                    </div>
                </div>
            </div>
            {!! Form::close() !!}

        </div>
    </div>
@endsection

@push('scripts')
<script type="text/javascript" src="{{ asset('assets/js/plugins/forms/selects/select2.min.js') }}"></script>
<script type="text/javascript" src="{{ asset('assets/js/plugins/forms/styling/uniform.min.js') }}"></script>
<script type="text/javascript" src="{{ asset('assets/js/core/app.js') }}"></script>
<script type="text/javascript" src="{{ asset('assets/js/pages/form_layouts.js') }}"></script>
@endpush

resources/views/backend/limitless/category/index.blade.php
@extends('backend.limitless.app')

{{--Begin Config--}}
@section('app.title','Shrym CMS - Admin Dashboard.')
{!! Form::component('fieldError', 'backend.limitless.partials.components.input-validate-error', ['name']) !!}
{{--End Config--}}

@section('content')
    <div class="row">
        <div class="col-md-4">
            <!— Basic layout—>
            {!! Form::model($user=null) !!}
            <div class="panel panel-flat">
                <div class="panel-heading">
                    <h5 class="panel-title">Create new categories</h5>
                </div>

                <div class="panel-body">
                    <div class="form-group">
                        <label>Name:</label>
                        {!! Form::text('name', '',['class' => 'form-control', 'placeholder' => 'Category Name']) !!}
                        @if ($errors->has('name'))
                            {!! Form::fieldError('name') !!}
                        @endif
                    </div>

                    <div class="form-group">
                        <label>Slug:</label>
                        {!! Form::text('slug', '',['class' => 'form-control', 'placeholder' => 'Category Slug']) !!}
                        <span class="help-block">Default slug is: <span id="default-slug" class="text-blue-700"></span></span>
                        @if ($errors->has('slug'))
                            {!! Form::fieldError('slug') !!}
                        @endif
                    </div>

                    <div class="form-group">
                        <label>Parrent Category:</label>
                        <select name="parent_id" class="select">
                            @foreach($categories as $cateKey => $category)
                                <option value="{{ $cateKey }}">{{ $category }}</option>
                            @endforeach
                        </select>
                        @if ($errors->has('parent_id'))
                            {!! Form::fieldError('parent_id') !!}
                        @endif
                    </div>

                    <div class="form-group">
                        <label class="display-block">Public:</label>

                        <label class="radio-inline">
                            {!! Form::radio('public', '1', true,['class'=>'styled']) !!} Active
                        </label>

                        <label class="radio-inline">
                            {!! Form::radio('public', '0', false, ['class'=>'styled']) !!} Not active
                        </label>
                    </div>

                    <div class="form-group">
                        <label>Description:</label>
                        {!! Form::textarea('description',null,['rows' => 5, 'cols' => 5, 'class' => 'form-control', 'placeholder' => 'Category description']); !!}
                    </div>

                    <div class="text-right">
                        <button type="submit" class="btn btn-primary">Create <i
                                    class="icon-arrow-right14 position-right"></i></button>
                    </div>
                </div>
            </div>
            {!! Form::close() !!}
            <!— /basic layout —>

        </div>
        <div class="col-md-8">
            <div class="panel panel-flat">
                <div class="panel-heading">
                    <h5 class="panel-title">Categories</h5>
                </div>

                <div class="panel-body">
                    List all categories in system.
                </div>

                <table class="table datatable-responsive-column-controlled">
                    <thead>
                    <tr>
                        <th>ID</th>
                        <th>Name</th>
                        <th>Slug</th>
                        <th>Parrent</th>
                        <th>Status</th>
                        <th class="text-center">Actions</th>
                    </tr>
                    </thead>
                    <tbody>
                    @foreach($tableCategoriesData as $category)
                        <tr>
                            <td></td>
                            <td>
                                <a href="{!! route('admin.categories.edit',$category->id) !!}">
                                    {!! str_repeat('—', $category->depth) . $category->name !!}
                                </a>
                            </td>
                            <td>{{ $category->slug }}</td>
                            <td>
                                @if(is_null($category->parent))
                                    —
                                @else
                                    {{ $category->parent->name }}
                                @endif
                            </td>
                            <td>
                                @if($category->public)
                                    <span class="label label-flat border-success text-success-600">Actived</span>
                                @else
                                    <span class="label label-flat border-danger text-danger-600">In Active</span>
                                @endif
                            </td>
                            <td class="text-center">
                                <ul class="icons-list">
                                    <li>
                                        <a href="{!! route('admin.categories.edit',$category->id) !!}">
                                            <i class="icon-pencil"></i>
                                        </a>
                                    </li>
                                    <li>
                                        {!! Form::open(array('action' => array('Backend\CategoryController@destroy', $category->id),'method'=>'DELETE',)) !!}
                                        <a href="#" class="remove-btn">
                                            <i class="icon-cross2"></i>
                                        </a>
                                        {!! Form::close() !!}
                                    </li>
                                </ul>
                            </td>
                        </tr>
                    @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>
@endsection

@push('scripts')
<script type="text/javascript" src="{{ asset('assets/js/plugins/forms/selects/select2.min.js') }}"></script>
<script type="text/javascript" src="{{ asset('assets/js/plugins/forms/styling/uniform.min.js') }}"></script>
<script type="text/javascript" src="{{ asset('assets/js/core/app.js') }}"></script>
<script type="text/javascript" src="{{ asset('assets/js/pages/form_layouts.js') }}"></script>
<script type="text/javascript" src="{{ asset('assets/js/plugins/tables/datatables/datatables.min.js') }}"></script>
<script type="text/javascript"
        src="{{ asset('assets/js/plugins/tables/datatables/extensions/responsive.min.js') }}"></script>
<script type="text/javascript" src="{{ asset('assets/js/backend/partials/datatable.js') }}"></script>
<script type="text/javascript" src="{{ asset('assets/js/backend/partials/helpers.js') }}"></script>
<script type="text/javascript" src="{{ asset('assets/js/backend/categories/index.js') }}"></script>
@endpush